## cachematrix.R
##
## This script contains two functions.  makeCacheMatrix is a function that returns
## a list of sub-functions that allow the inverse of an input matrix to be stored 
## and retrieved.  cacheSolve retrieves the stored inverse from such a list; 
## if there is no stored inverse, the inverse is calculated and stored.

## makeCacheMatrix takes a matrix as input and returns a list of three 
## sub-functions - get, setInverse, and getInverse.  get returns the input matrix,
## setInverse updates an inverse value stored due to lexical scoping, and getInverse
## returns the current inverse value.  

## Note: The set function was not implemented because it isn't necessary to get
## the results desired here.

makeCacheMatrix <- function(x = matrix()) {
    inverse <- NULL
    get <- function() x
    setInverse <- function(inverse_) inverse <<- inverse_
    getInverse <- function() inverse
    list(get=get, setInverse=setInverse, getInverse=getInverse)
}


## cacheSolve takes a list of the form generated by makeCacheMatrix, and returns
## the inverse of the matrix retrieved by the get function in the input list.  If
## the inverse value obtained by getInverse is null, this function will use the
## solve() function to generate the inverse of the matrix and store it with 
## setInverse.  Otherwise, it will simply return the value that was cached before,
## using getInverse.

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    data <- x$get()
    inv <- x$getInverse()
    result <- NULL
    if(is.null(inv)) {
        message("no cached data found, calculating inverse...")
        result <- x$setInverse(solve(data))
    }
    else {
        message("using cached data...")
        result <- inv
    }
    result
}
